add new sccs_unedit() function that handles the checkout preferences correctly, and doesn't rewrite the gfile if it hasn't changed.
BUGID:  2002-03-01-001  2002-02-08-009

bk: 3c87c099j4ECIzNMfhaBJ1Xhimnnpg

diff --git a/src/t/setup b/src/t/setup
--- a/src/t/setup
+++ b/src/t/setup
@@ -64,7 +64,7 @@ no_logging() {
 	echo "email: nobody@nowhere.bk" >> c
 	echo "eoln: unix" >> c
 	echo "keyword: sccs" >> c
-	bk setup -f -cc $1
+	bk setup -f -cc $1 || { echo "Setup failed!"; exit 1; }
 	cd $1
 }
 
