A tiny cset (yeah, right) which adds support for different eulas. We add the eula type to the leases so we can print the eula type in bk version. I added a -a option to setup which auto-accepts the license.
bk: 42e1472avcVkhnK2d0uwJw4RI0A84g

diff --git a/src/t/setup b/src/t/setup
--- a/src/t/setup
+++ b/src/t/setup
@@ -74,8 +74,32 @@ no_logging() {
 	echo "email: nobody@nowhere.bk" >> c
 	echo "eoln: unix" >> c
 	echo "keyword: sccs" >> c
-	bk setup -f -cc $1 || { echo "Setup failed!"; exit 1; }
+	bk setup -a -f -cc $1 || {
+		echo "Setup failed!"
+		exit 1
+	}
 	cd $1
+	bk _eula -a
+	touch BitKeeper/etc/SCCS/x.marked
+}
+
+commercial() {
+	echo "logging: none" > c
+	echo "description: BitKeeper Test repository" >> c
+	echo "email: nobody@nowhere.bk" >> c
+	echo "eoln: unix" >> c
+	echo "keyword: sccs" >> c
+	echo "license: $BKL_PRO" >> c
+	echo "licsign1: $BKL_P1" >> c
+	echo "licsign2: $BKL_P2" >> c
+	echo "licsign3: $BKL_P3" >> c
+	BK_HOST=bk_regression.bitkeeper.com bk setup -a -f -cc $1 || {
+		echo "Setup failed!"
+		exit 1
+	}
+	cd $1
+	bk _eula -a
+	touch BitKeeper/etc/SCCS/x.marked
 }
 
 echon() {
