Tons of performance fixes in citool.  Rewrite the ignore code in citool to give the user a dialog.  Keep the GUI responsive through long BK operations.
bk: 5155909bj8iKv6mro7C0lG1BYCjIUQ

diff --git a/src/t/setup b/src/t/setup
--- a/src/t/setup
+++ b/src/t/setup
@@ -353,5 +353,23 @@ fail() {
 	}
 	exit 1
 }
+
+test_gui_result() {
+	rc_got=$1
+	rc_expect=$2
+	OUT="$3"
+
+	test $rc_got -ne $rc_expect -o -s "$OUT" && {
+		echo "failed"
+		test $rc_got -ne $rc_expect && {
+			echo "exited $rc_got; expected $rc_expect"
+		}
+		test -s "$OUT" && {
+			cat "$OUT"
+		}
+		exit 1
+	}
+	echo "OK"
+}
 # this next line needs to be last, it's line zero of the script (see doit)
 BOS=$LINENO
