Resolve problems with previous merges.
Rework all the license and lease interfaces to use
one small set rather than several overlapping functions.

new
   proj_bkl  (was proj_license)
   proj_bklbits (was proj_licensebits)

gone
   bk_mode
   bk_optons
   bkcl
   bkcl_type

Add new IMPORT license option to restrict sccs2bk imports.

There are still several open issues, but this code at least
seems to work.

bk: 42e5450cKVKHqEYrthJM7iOKZcQ3wQ

diff --git a/src/t/setup b/src/t/setup
--- a/src/t/setup
+++ b/src/t/setup
@@ -73,8 +73,6 @@ license: $BKL_PRO
 licsign1: $BKL_P1
 licsign2: $BKL_P2
 licsign3: $BKL_P3
-logging: none
-logging_ask: no
 description: BitKeeper Test repository
 email: nobody@nowhere.bk
 eoln: unix
@@ -89,9 +87,10 @@ _make_repo() {
 	SFIO=$3
 	REPO=$BK_CACHE/${TYPE}
 
-        if [ -d "$REPO" ]; then rm -rf "$REPO"; fi 	# should not happen
-        BK_LICENSE=ACCEPTED bk setup -a -f -c"$CF" "$REPO" || {
-                echo "Setup failed!"; exit 1;
+	test -d "$REPO" && rm -rf "$REPO"		# should not happen
+	bk setup -a -f -c"$CF" "$REPO" || {
+		echo "Setup failed!"
+		exit 1
         }
 	# Make a cached copy
         (cd "$REPO" && find . -type f | bk sfio -qm -o > "$SFIO")
@@ -104,13 +103,12 @@ _get_cached_repo() {
 	bk sfio -qm -i < "$2"
 	mkdir -p BitKeeper/tmp 		# because sfio does not copy dir
 	mkdir -p BitKeeper/deleted/SCCS 	
-	mkdir -p BitKeeper/etc/.master
+	bk _eula -a
 }
 
 # Get a commercial repo, use cache copy if available
 # Usage: commercial dir
 commercial() {
-	
 	CF="$BK_CACHE"/commercial.config
 	SFIO=$BK_CACHE/commercial.sfio
 	test -f "$SFIO" || {
